import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {createStairs,createLandingRail,stairOpening,FLOOR_RISE} from './stairs.js';
import {enhanceHouse,roomNames,furnitureNames} from './references.js';
const $=s=>document.querySelector(s), host=$('#canvas');
const scene=new T.Scene();scene.background=new T.Color('#e9eeef');
const camera=new T.PerspectiveCamera(38,1,.1,200);const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.85;host.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI/2.08;controls.minDistance=3;controls.maxDistance=45;controls.target.set(5,0,7.5);
scene.add(new T.HemisphereLight(0xffffff,0x8b9ba2,2.6));const sun=new T.DirectionalLight(0xfff2df,3.3);sun.position.set(-8,22,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-20,right:20,top:20,bottom:-20});sun.shadow.bias=-.0005;sun.shadow.normalBias=.025;sun.shadow.radius=3;scene.add(sun);
const mat=(c,roughness=.8)=>new T.MeshStandardMaterial({color:c,roughness});const white=mat('#f5f3ed'),wood=mat('#bda58a'),fabric=mat('#c3c5bf'),dark=mat('#34464b'),metal=mat('#6d777a'),glass=new T.MeshStandardMaterial({color:'#a0c7d4',transparent:true,opacity:.3,roughness:.15});
function box(parent,w,h,d,x,y,z,m=white){const q=new T.Mesh(new T.BoxGeometry(w,h,d),m);q.position.set(x,y,z);q.castShadow=true;q.receiveShadow=true;parent.add(q);return q;}
function cylinder(parent,r,h,x,y,z,m){const q=new T.Mesh(new T.CylinderGeometry(r,r,h,24),m);q.position.set(x,y,z);q.castShadow=true;parent.add(q);return q;}
const floors=[new T.Group(),new T.Group()];floors.forEach(g=>scene.add(g));let current='0',height=1.1,editing=false,selected=null;const walls=[],furniture=[],rooms=[];
const P=(arr,f)=>arr.map(([x,z])=>f===0?[(x-444)/61,(z-49)/61]:[(x-96)/63+.3,(z-49)/63]);
function slab(g,p,color,y=-.055,hole=false){const sh=new T.Shape(p.map(([x,z])=>new T.Vector2(x,-z)));if(hole){const h=new T.Path(stairOpening.map(([x,z])=>new T.Vector2(x,-z)));sh.holes.push(h);}const mesh=new T.Mesh(new T.ExtrudeGeometry(sh,{depth:.11,bevelEnabled:false}),mat(color));mesh.rotation.x=-Math.PI/2;mesh.position.y=y;mesh.receiveShadow=true;g.add(mesh);return mesh;}
function segment(g,a,b,kind='wall'){const dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz);if(len<.01)return;const group=new T.Group();group.position.set((a[0]+b[0])/2,0,(a[1]+b[1])/2);group.rotation.y=-Math.atan2(dz,dx);g.add(group);if(kind==='wall'){const m=box(group,len,1,.13,0,.5,0);walls.push(m);}else if(kind==='window'){box(group,len,.07,.15,0,.08,0,metal);box(group,len,1.3,.04,0,.76,0,glass);box(group,.05,1.4,.12,-len/2,.75,0,white);box(group,.05,1.4,.12,len/2,.75,0,white);box(group,len,.06,.12,0,1.45,0,white);const sill=box(group,len,.7,.13,0,.35,0);walls.push(sill);sill.userData.cap=.7;}else{box(group,len,.025,.16,0,.015,0,wood);const door=box(group,.045,.65,len*.88,-len/2,.325,-len*.44,wood);door.rotation.y=-.3;}}
function edge(g,a,b,opening){if(!opening)return segment(g,a,b);const [t,u,k]=opening;const lerp=n=>[a[0]+(b[0]-a[0])*n,a[1]+(b[1]-a[1])*n];segment(g,a,lerp(t));if(k==='garage'){const aa=lerp(t),bb=lerp(u);box(g,Math.hypot(bb[0]-aa[0],bb[1]-aa[1]),.08,.14,(aa[0]+bb[0])/2,.1,(aa[1]+bb[1])/2,metal);}else segment(g,lerp(t),lerp(u),k);segment(g,lerp(u),b);}
function label(g,text,x,z){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.font='500 27px Arial';ctx.textAlign='center';ctx.fillStyle='#40545c';ctx.fillText(text,256,54);const tex=new T.CanvasTexture(c);const q=new T.Mesh(new T.PlaneGeometry(3.4,.85),new T.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false}));q.rotation.x=-Math.PI/2;q.position.set(x,.065,z);g.add(q);}
function room(f,id,name,area,pixels,openings={},color='#d8c7af'){const p=P(pixels,f),g=floors[f];const surface=slab(g,p,color,-.055,id==='1-7');const first=g.children.length;p.forEach((a,i)=>edge(g,a,p[(i+1)%p.length],openings[i]));const groups=g.children.slice(first);const center=p.reduce((a,b)=>[a[0]+b[0]/p.length,a[1]+b[1]/p.length],[0,0]);const r={f,id,name:roomNames[id]||name,area,p,center,surface,groups};rooms.push(r);label(g,`${id} · ${area.replace('.',',')} m²`,center[0],center[1]);return r;}
room(0,'1-4','Living & dining','36.78',[[484,80],[1083,80],[1083,321],[550,321],[515,197]],{0:[.67,.82,'window'],2:[.35,.5,'door'],4:[.15,.65,'window']});
room(0,'1-3','Study','3.83',[[553,338],[778,338],[778,493],[595,493]],{1:[.35,.75,'door'],3:[.25,.7,'window']});
room(0,'1-1','Entrance','4.99',[[599,506],[778,506],[778,615],[631,615]],{1:[.3,.8,'door'],2:[.35,.75,'door']},'#d3d4ce');
room(0,'1-2','Hall & stairs','9.35',[[788,338],[934,338],[934,616],[788,616]],{0:[0,.55,'door'],1:[.3,.62,'door'],3:[.18,.43,'door']},'#ded7c9');
room(0,'1-5','Kitchen','6.58',[[950,350],[1140,350],[1140,475],[950,475]],{1:[.55,.95,'door'],3:[.35,.95,'door']},'#deddd6');
room(0,'1-6','Utility / WC','6.45',[[950,487],[1140,487],[1140,610],[950,610]],{1:[.16,.45,'window'],3:[.15,.65,'door']},'#d3d4ce');
room(0,'G-1','Garage','35.11',[[641,641],[1076,641],[1076,957],[725,957]],{1:[.5,.68,'window'],2:[.17,.84,'garage'],0:[.05,.2,'door']},'#b9c0c1');
room(1,'1-8','Bedroom 1','19.77',[[120,75],[464,75],[464,226],[420,226],[420,323],[120,323]],{3:[.15,.85,'door'],4:[.5,.98,'window'],5:[.15,.65,'window']});
room(1,'1-9','Bedroom 2','15.06',[[475,75],[742,75],[742,323],[532,323],[532,226],[475,226]],{0:[.24,.58,'window'],3:[.13,.9,'door']});
room(1,'1-7','Landing','14.64',[[430,238],[522,238],[522,338],[590,338],[590,628],[369,628],[369,476],[421,476],[421,338],[430,338]],{0:[.1,.9,'door'],4:[.25,.8,'door'],6:[0,.95,'window'],2:[0,.95,'door'],9:[0,.95,'door']},'#ded7c9');
room(1,'1-11','Bathroom','12.48',[[610,350],[807,350],[807,622],[610,622]],{1:[.25,.39,'window'],3:[.03,.3,'door']},'#d2d8d6');
room(1,'1-14','Dressing area','2.70',[[443,649],[591,649],[591,718],[443,718]],{0:[.15,.83,'door'],2:[.05,.48,'door']},'#ded7c9');
room(1,'1-13','Bedroom 3','15.34',[[280,649],[431,649],[431,727],[521,727],[521,991],[373,991]],{2:[.05,.65,'door'],5:[.28,.65,'window']});
room(1,'1-12','Bedroom 4','17.24',[[604,649],[743,649],[743,991],[531,991],[531,727],[604,727]],{2:[.3,.65,'window'],4:[.1,.8,'door']});
function piece(f,type,x,z,w=1,d=1,rot=0){const g=new T.Group();g.position.set(x,0,z);g.rotation.y=rot;g.userData={type,f,w,d,initial:[x,z,rot]};floors[f].add(g);furniture.push(g);const legs=(ww,dd,h=.38)=>{for(const a of[-1,1])for(const b of[-1,1])box(g,.055,h,.055,a*(ww/2-.1),h/2,b*(dd/2-.1),dark);};
if(type==='Sofa'){box(g,w,.35,d,0,.37,0,fabric);box(g,w,.5,.18,0,.7,-d/2+.06,fabric);for(const a of[-1,1])box(g,.16,.45,d,a*(w/2-.08),.55,0,fabric);for(let i=0;i<3;i++)box(g,w/3-.08,.1,d*.68,-w/3+i*w/3,.6,.05,white);legs(w,d,.2);}
else if(type.startsWith('Bed')){box(g,w,.28,d,0,.23,0,wood);box(g,w-.07,.22,d-.1,0,.47,0,white);box(g,w,.85,.12,0,.48,-d/2,fabric);box(g,w-.05,.055,d*.52,0,.61,d*.18,fabric);for(const a of[-1,1])box(g,w*.4,.12,.4,a*w*.24,.63,-d*.32,white);}
else if(type==='Dining table'||type==='Desk'||type==='Coffee table'){const h=type==='Coffee table'?.4:.74;box(g,w,.08,d,0,h,0,wood);legs(w,d,h);}
else if(type==='Chair'){box(g,.44,.1,.45,0,.48,0,fabric);box(g,.44,.5,.08,0,.75,-.2,fabric);legs(.43,.43,.43);}
else if(type==='Wardrobe'){box(g,w,1.85,d,0,.925,0,white);for(let i=0;i<Math.ceil(w/.6);i++)box(g,.016,1.75,.02,-w/2+i*.6,.925,d/2+.01,wood);}
else if(type==='Kitchen counter'){box(g,w,.84,d,0,.42,0,white);box(g,w+.04,.07,d+.04,0,.88,0,wood);box(g,.5,.025,.38,0,.93,0,metal);}
else if(type==='Bath'){box(g,w,.5,d,0,.27,0,white);box(g,w-.18,.03,d-.18,0,.535,0,mat('#a7bdc2'));}
else if(type==='Shower'){box(g,w,.07,d,0,.05,0,white);box(g,.025,1.85,d,-w/2,.98,0,glass);box(g,w,1.85,.025,0,.98,-d/2,glass);}
else if(type==='WC'){box(g,.38,.65,.27,0,.35,-.2,white);cylinder(g,.22,.4,0,.23,.08,white);}
else if(type==='Plant'){cylinder(g,.18,.32,0,.16,0,wood);const leaves=new T.Mesh(new T.SphereGeometry(.33,12,10),mat('#617964'));leaves.scale.y=1.6;leaves.position.y=.65;g.add(leaves);}
else if(type==='Garage storage'){box(g,w,1.5,d,0,.75,0,metal);for(let i=1;i<4;i++)box(g,w,.03,d+.02,0,i*.37,0,wood);}
g.traverse(m=>{if(m.isMesh)m.userData.furniture=g;});return g;}
piece(0,'Sofa',4.5,1.2,2.5,.92);piece(0,'Coffee table',4.5,2.4,1.1,.6);piece(0,'Dining table',8.2,2.25,1.45,.85);for(const z of[1.5,3])for(const x of[7.75,8.65])piece(0,'Chair',x,z,1,1,z<2?Math.PI:0);piece(0,'Plant',9.85,.7);piece(0,'Desk',3.4,5.15,1.2,.55);piece(0,'Chair',3.4,5.9);piece(0,'Wardrobe',4.7,8.6,.7,.45);piece(0,'Kitchen counter',9.7,5.5,2.2,.6);piece(0,'Kitchen counter',10.65,6.3,.6,1);piece(0,'WC',10.7,7.7);piece(0,'Bath',9.4,8.6,.7,.5);piece(0,'Garage storage',9.8,11.2,.5,1.8);
piece(1,'Bed · bedroom 1',2.1,1.6,1.6,2);piece(1,'Wardrobe',4.75,.8,1.3,.55);piece(1,'Desk',1.2,3.55,1.15,.5);piece(1,'Chair',1.2,2.95,1,1,Math.PI);piece(1,'Bed · bedroom 2',9,2.1,1.6,2);piece(1,'Wardrobe',6.8,.9,1.1,.55);piece(1,'Bed · bedroom 3',5,13.3,1.4,2);piece(1,'Wardrobe',3.8,10.1,1.15,.55);piece(1,'Bed · bedroom 4',9.3,13.1,1.6,2);piece(1,'Wardrobe',9.6,10.2,1.1,.55);piece(1,'Shower',8.95,5.55,1,1);piece(1,'Bath',10.8,6.1,.72,1.65);piece(1,'WC',8.8,7);piece(1,'Kitchen counter',10,8.65,1.2,.5);piece(1,'Plant',5.4,8.7);
const reference=enhanceHouse({scene,floors,rooms,walls,furniture,box,cylinder,mat,white,wood,metal,glass});
const stair=createStairs({wood,metal});floors[0].add(stair);const stairUpper=stair.clone(true);stairUpper.position.y=-FLOOR_RISE;floors[1].add(stairUpper);floors[1].add(createLandingRail({wood,metal}));
const ground=box(scene,70,.12,70,4,-.34,7,mat('#dce2df'));ground.receiveShadow=true;
let mode='interior';
const highlight=new T.BoxHelper(new T.Object3D(),0xb47b41);scene.add(highlight);highlight.visible=false;
function setHeight(){walls.forEach(m=>{const h=Math.min(mode==='exterior'?2.8:height,m.userData.cap??2.8);m.scale.y=h/(m.geometry.parameters.height||1);m.position.y=h/2;m.visible=h>0;});$('#wallvalue').value=height.toFixed(1).replace('.',',')+' m';reference.setCutaway(mode==='interior',height);}setHeight();
function overview(){if(mode==='exterior'){controls.target.set(3.4,1.4,5.7);camera.position.set(-24,21,29);controls.maxDistance=70;}else{controls.maxDistance=45;controls.target.set(5.8,current==='both'?2:0,7.5);camera.position.set(23,current==='both'?26:22,29);}if(camera.aspect<1.15){camera.position.sub(controls.target).multiplyScalar(Math.min(2.5,1.15/camera.aspect)).add(controls.target);controls.maxDistance=120;}controls.update();}
function selectPiece(p){selected=p;$('#selection').hidden=!p;highlight.visible=!!p;if(p){$('#selectedName').textContent=p.userData.label||furnitureNames[p.userData.type]||'Baldas · apytikslis';highlight.setFromObject(p);}}
function setFloor(f){if(!['0','1','both'].includes(f))throw Error('Neteisingas aukštas');current=f;floors.forEach((g,i)=>{g.visible=mode==='exterior'||f==='both'||f===String(i);g.position.y=mode==='exterior'||f==='both'?i*FLOOR_RISE:0;});stairUpper.visible=mode==='interior'&&f==='1';selectPiece(null);document.querySelectorAll('[data-floor]').forEach(b=>{b.classList.toggle('active',b.dataset.floor===f);b.setAttribute('aria-pressed',b.dataset.floor===f);});$('#floorLabel').textContent=mode==='exterior'?'SKLYPAS IR NAMAS':f==='both'?'01 + 02 / ABU AUKŠTAI':f==='0'?'01 / PIRMAS AUKŠTAS':'02 / ANTRAS AUKŠTAS';$('#views').innerHTML=mode==='exterior'?'<option value="overview">Visas sklypas</option><option value="garden">Kiemo fasadas</option><option value="drive">Įvažiavimas</option><option value="terrace">Terasa ir pirties priestatas ≈</option><option value="balcony">Balkonas ≈</option>':'<option value="overview">'+(f==='both'?'Visas namas':'Visas aukštas')+'</option><option value="stairs">Laiptai tarp aukštų ≈</option>'+rooms.filter(r=>f==='both'||String(r.f)===f).map(r=>`<option value="${r.id}">${r.id} · ${r.name}</option>`).join('');overview();}setFloor('0');
function setMode(next){mode=next;reference.exterior.visible=mode==='exterior';reference.roof.visible=$('#roof').checked;$('#exteriorOptions').hidden=mode!=='exterior';$('#interiorOptions').hidden=mode==='exterior';if(editing)$('#edit').onclick();$('#edit').disabled=mode==='exterior';document.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===mode);b.setAttribute('aria-pressed',b.dataset.mode===mode);});setHeight();setFloor(current);}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('#roof').onchange=e=>reference.roof.visible=e.target.checked;setMode('exterior');
document.querySelectorAll('[data-floor]').forEach(b=>b.onclick=()=>setFloor(b.dataset.floor));$('#walls').oninput=e=>{height=+e.target.value;setHeight();};$('#views').onchange=e=>{if(mode==='exterior'){const presets={garden:[[0,2,7],[-17,8,15]],drive:[[7,1,14],[10,10,29]],terrace:[[-2,1,-1],[-12,10,6]],balcony:[[2,3.4,6.6],[-7,9,12]]};const p=presets[e.target.value];if(!p)return overview();controls.target.set(...p[0]);camera.position.set(...p[1]);return;}if(e.target.value==='stairs'){controls.target.set(7.25,current==='1'?.2:1.4,6.3);camera.position.set(1.4,current==='1'?5.8:6.8,11.5);return;}const r=rooms.find(r=>r.id===e.target.value);if(!r)return overview();const y=floors[r.f].position.y;controls.target.set(r.center[0],y,r.center[1]);camera.position.set(r.center[0]+5,y+8,r.center[1]+7);};$('#home').onclick=overview;$('#zoomIn').onclick=()=>camera.position.sub(controls.target).multiplyScalar(.8).add(controls.target);$('#zoomOut').onclick=()=>camera.position.sub(controls.target).multiplyScalar(1.25).add(controls.target);
$('#edit').onclick=()=>{editing=!editing;$('#edit').classList.toggle('on',editing);$('#edit').setAttribute('aria-pressed',editing);$('#edit').textContent=editing?'Baigti keitimą':'Keisti baldus';$('#editHint').textContent=editing?'Pasirinkite baldą ir tempkite arba naudokite rodykles. Pasukimas – po 15°.':'Įjunkite keitimą, tada pasirinkite baldą. Lauko įranga ir įmontuoti elementai yra fiksuoti.';if(!editing)selectPiece(null);};
function inside(x,z,p){let c=false;for(let i=0,j=p.length-1;i<p.length;j=i++){if(((p[i][1]>z)!==(p[j][1]>z))&&(x<(p[j][0]-p[i][0])*(z-p[i][1])/(p[j][1]-p[i][1])+p[i][0]))c=!c;}return c;}
function move(p,x,z){const r=rooms.find(r=>r.f===p.userData.f&&inside(p.position.x,p.position.z,r.p));if(r&&!inside(x,z,r.p))return; p.position.x=x;p.position.z=z;highlight.setFromObject(p);}
document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{if(selected){const [x,z]=b.dataset.move.split(',').map(Number);move(selected,selected.position.x+x,selected.position.z+z);}});$('#rotate').onclick=()=>{if(selected){selected.rotation.y+=Math.PI/12;highlight.setFromObject(selected);}};$('#reset').onclick=()=>{furniture.forEach(p=>{const[x,z,a]=p.userData.initial;p.position.set(x,0,z);p.rotation.y=a;});selectPiece(null);overview();};
const ray=new T.Raycaster(),pointer=new T.Vector2(),plane=new T.Plane(),hit=new T.Vector3();let dragging=false,offset=new T.Vector3();function point(e){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);}
renderer.domElement.addEventListener('pointerdown',e=>{if(!editing||mode==='exterior')return;point(e);const hits=ray.intersectObjects(furniture.filter(p=>floors[p.userData.f].visible),true);if(!hits.length){selectPiece(null);return;}selectPiece(hits[0].object.userData.furniture);if(!selected)return;dragging=true;controls.enabled=false;plane.set(new T.Vector3(0,1,0),-floors[selected.userData.f].position.y);ray.ray.intersectPlane(plane,hit);offset.copy(selected.position).sub(hit);renderer.domElement.setPointerCapture(e.pointerId);},{capture:true});renderer.domElement.addEventListener('pointermove',e=>{if(!dragging||!selected)return;point(e);if(ray.ray.intersectPlane(plane,hit))move(selected,hit.x+offset.x,hit.z+offset.z);});function release(){dragging=false;controls.enabled=true;}renderer.domElement.addEventListener('pointerup',release);renderer.domElement.addEventListener('pointercancel',release);
let narrowViewport;new ResizeObserver(()=>{const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();const narrow=w<600;if(narrowViewport!==narrow){narrowViewport=narrow;overview();}}).observe(host);renderer.setAnimationLoop(()=>{controls.update();if(selected)highlight.setFromObject(selected);renderer.render(scene,camera);});
if(document.modelContext?.registerTool){const life=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'set_house_floor',description:'Rodyti pirmą, antrą arba abu namo aukštus.',inputSchema:{type:'object',properties:{floor:{type:'string',enum:['0','1','both']}},required:['floor'],additionalProperties:false},annotations:{readOnlyHint:false},execute:({floor})=>{if(!['0','1','both'].includes(floor))throw Error('Neteisingas aukštas');setMode('interior');setFloor(floor);return{floor:current};}},{signal:life.signal})).catch(()=>{});addEventListener('pagehide',()=>life.abort());}catch{}}
